name: Python Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unittest:
    name: Run unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install bfio 🔧
        run: |
          pip install .[dev]
      - name: Test with unittest
        run: |
          python -m unittest -v
